print("Hey, what's your first name: ")
first_name=input()
print("And your last name: ")
last_name=input()
whole_name=first_name.strip() + " " + last_name.strip()
print("Well, pleased to meet you, " + first_name + " " + last_name)
